services:
  postgres:
    image: postgres:16
    container_name: seguros-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d
    networks:
      - seguros-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: seguros-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - seguros-net

volumes:
  postgres_data:

networks:
  seguros-net:
    driver: bridge
